name: tk_decoding
channels:
- rapidsai
- conda-forge
- nvidia
- edeno
- defaults
dependencies:
- "python>=3.9"
- numpy
- scipy
- scikit-learn
- matplotlib
- xarray
- pandas
- replay_trajectory_classification
- trajectory_analysis_tools
- cupy
- ripple_detection
- seaborn
- dask
- dask-cuda
- tqdm
- statsmodels
- patsy
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- black
- pip
- pip:
  - sortingview
  - mountainlab-pytools